/**
 * Legal Consultation Prep-Pack Generator.
 *
 * Implements TECH.md §2, §5.4:
 * Assembles a structured briefing document designed to take to an advocate,
 * lawyer, or Legal Services Authority consultation.
 */
import type { ParsedDocument, Triage, ClauseFinding, MissingFinding } from '@/lib/types';

export interface PrepPackOptions {
  doc: ParsedDocument;
  triage: Triage | null;
  findings: ClauseFinding[];
  missingFindings: MissingFinding[];
}

export function generatePrepPack(opts: PrepPackOptions): string {
  const { doc, triage, findings, missingFindings } = opts;
  const dateStr = new Date().toISOString().split('T')[0];

  let pack = `# PlainClause Legal Consultation Briefing Pack\n\n`;
  pack += `**Document**: ${doc.filename} | **Date**: ${dateStr}\n`;
  if (triage) {
    pack += `**Document Type**: ${triage.documentType} | **Jurisdiction**: ${triage.jurisdiction}\n`;
  }
  pack += `\n---\n\n`;

  pack += `## 1. Executive Summary for Legal Counsel\n\n`;
  pack += `The user has reviewed this agreement using PlainClause automated comprehension tools. `;
  pack += `A total of **${findings.filter((f) => f.severity === 'high').length} high-severity** contractual terms `;
  pack += `and **${missingFindings.length} missing statutory protections** were flagged for your professional review.\n\n`;

  pack += `## 2. Specific Questions for Your Advocate\n\n`;
  let qNum = 1;
  for (const f of findings.filter((f) => f.severity === 'high')) {
    pack += `${qNum++}. **Regarding Clause #${f.clauseId} (${f.title}):** ${f.whyItMatters} *Is this enforceability risk acceptable under local practice?*\n`;
  }
  for (const m of missingFindings) {
    pack += `${qNum++}. **Regarding Missing Protection (${m.title}):** *How should we insert the requested clause (${m.suggestedAsk}) into the draft?*\n`;
  }
  pack += `\n`;

  pack += `## 3. High-Risk Clauses & Verbatim Extracts\n\n`;
  for (const f of findings.filter((f) => f.severity === 'high' || f.severity === 'medium')) {
    const clause = doc.clauses.find((c) => c.id === f.clauseId);
    pack += `### Clause #${f.clauseId}: ${f.title} (${f.severity.toUpperCase()})\n`;
    if (clause) {
      pack += `> "${clause.text.trim()}"\n\n`;
    }
    pack += `- **Risk**: ${f.whyItMatters}\n`;
    if (f.suggestedAsk) {
      pack += `- **Proposed Amendment**: ${f.suggestedAsk}\n`;
    }
    if (f.jurisdictionNote) {
      pack += `- **Statutory Reference**: ${f.jurisdictionNote}\n`;
    }
    pack += `\n`;
  }

  pack += `---\n*Generated by PlainClause. Strictly for preparation purposes.*`;
  return pack;
}
